name: ASN-Processor Update

on:
  push:
    branches: [ "main" ]

  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx16G

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run Program
        run: mvn -ntp -B clean compile exec:java -D"exec.mainClass"="io.github.secwrk.addr.asn.ASNProcessor"
        with:
          default_author: github_actions
          message: 'ASN.csv Updated'
          add: 'generated/ASN.csv'
