name: Sync

on:
  push:
    branches: [ "main" ]

  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx16G

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Run CloudASNFilteredProcessor
        run: mvn -ntp -B clean compile exec:java -D"exec.mainClass"="io.github.secwrk.addr.asn.CloudASNFilteredProcessor"
      - name: Run ASNProcessor
        run: mvn -ntp -B clean compile exec:java -D"exec.mainClass"="io.github.secwrk.addr.asn.ASNProcessor"
      - name: Run CityProcessor
        run: mvn -ntp -B clean compile exec:java -D"exec.mainClass"="io.github.secwrk.addr.city.CityProcessor"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          default_author: github_actions
          message: 'Sync'
          add: 'generated'
